// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: mmo/v1/cluster.proto

package mmov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BusEnvelope wraps a payload with the addressing a request needs.
//
// The bus is publish/subscribe, which has no notion of a reply. Request and
// response is built on top: the requester subscribes to a private inbox
// subject, names it here, and the responder publishes there.
type BusEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ReplyTo is the subject a response should be published to. Empty for a
	// one-way publish.
	ReplyTo string `protobuf:"bytes,1,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	// CorrelationId matches a response to its request. Necessary even with a
	// private inbox, because a late reply to a timed-out request would
	// otherwise be mistaken for the answer to the next one.
	CorrelationId string `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Payload       []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// Error carries a failure back to the requester, so a responder can refuse
	// without the requester waiting out its timeout.
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BusEnvelope) Reset() {
	*x = BusEnvelope{}
	mi := &file_mmo_v1_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusEnvelope) ProtoMessage() {}

func (x *BusEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_v1_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusEnvelope.ProtoReflect.Descriptor instead.
func (*BusEnvelope) Descriptor() ([]byte, []int) {
	return file_mmo_v1_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *BusEnvelope) GetReplyTo() string {
	if x != nil {
		return x.ReplyTo
	}
	return ""
}

func (x *BusEnvelope) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BusEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BusEnvelope) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// TransferRequest hands a character from one world node to another.
//
// The protocol is the same whether the destination is on this node or another
// one. A local fast path would mean the distributed path is never exercised
// until the day it has to work (docs/architecture.md, AGENTS.md invariant 2).
type TransferRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	CharacterId string                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	AccountId   string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Name        string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Where the character is going.
	//
	// spawn_point names an entrance; waypoint_id names a fast-travel
	// destination, which the destination resolves from its own copy of the
	// content rather than trusting coordinates off the wire. Both empty means
	// the character keeps the position in state, which is what a channel switch
	// wants: the same map, the same spot, a different instance.
	MapId      string `protobuf:"bytes,4,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	SpawnPoint string `protobuf:"bytes,5,opt,name=spawn_point,json=spawnPoint,proto3" json:"spawn_point,omitempty"`
	InstanceId uint64 `protobuf:"varint,6,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	WaypointId string `protobuf:"bytes,12,opt,name=waypoint_id,json=waypointId,proto3" json:"waypoint_id,omitempty"`
	// Progression, which has its own database columns.
	Level uint32 `protobuf:"varint,7,opt,name=level,proto3" json:"level,omitempty"`
	Exp   int64  `protobuf:"varint,8,opt,name=exp,proto3" json:"exp,omitempty"`
	Gold  int64  `protobuf:"varint,9,opt,name=gold,proto3" json:"gold,omitempty"`
	// The simulation state -- position, velocity, vitals -- as stored.
	State []byte `protobuf:"bytes,10,opt,name=state,proto3" json:"state,omitempty"`
	// The fencing token the source holds. The destination refuses a token that
	// is not at least as high as one it has already seen, which is what stops a
	// replayed or delayed transfer resurrecting a character somewhere it has
	// already left.
	LeaseToken    int64 `protobuf:"varint,11,opt,name=lease_token,json=leaseToken,proto3" json:"lease_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_mmo_v1_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_v1_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_mmo_v1_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *TransferRequest) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *TransferRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *TransferRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TransferRequest) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *TransferRequest) GetSpawnPoint() string {
	if x != nil {
		return x.SpawnPoint
	}
	return ""
}

func (x *TransferRequest) GetInstanceId() uint64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *TransferRequest) GetWaypointId() string {
	if x != nil {
		return x.WaypointId
	}
	return ""
}

func (x *TransferRequest) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *TransferRequest) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *TransferRequest) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *TransferRequest) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *TransferRequest) GetLeaseToken() int64 {
	if x != nil {
		return x.LeaseToken
	}
	return 0
}

type TransferReply struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Accepted bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// The entity the character was given in its new room.
	EntityId uint32 `protobuf:"varint,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	// Which node accepted it, for logging and for routing afterwards.
	NodeId        string `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferReply) Reset() {
	*x = TransferReply{}
	mi := &file_mmo_v1_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferReply) ProtoMessage() {}

func (x *TransferReply) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_v1_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferReply.ProtoReflect.Descriptor instead.
func (*TransferReply) Descriptor() ([]byte, []int) {
	return file_mmo_v1_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *TransferReply) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *TransferReply) GetEntityId() uint32 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *TransferReply) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *TransferReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// RoomClosed announces that an instance has been torn down, so the directory
// and anything holding a handle can stop referring to it.
type RoomClosed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    uint64                 `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	MapId         string                 `protobuf:"bytes,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomClosed) Reset() {
	*x = RoomClosed{}
	mi := &file_mmo_v1_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomClosed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomClosed) ProtoMessage() {}

func (x *RoomClosed) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_v1_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomClosed.ProtoReflect.Descriptor instead.
func (*RoomClosed) Descriptor() ([]byte, []int) {
	return file_mmo_v1_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *RoomClosed) GetInstanceId() uint64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *RoomClosed) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *RoomClosed) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// HostRequest asks a node to start hosting a room instance.
//
// Needed because the directory, not the caller, decides which node hosts a
// room. A gateway placing a player into a map may be told the instance belongs
// to a node other than its own, and that node has to be running the room
// before anyone can join it.
type HostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    uint64                 `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	MapId         string                 `protobuf:"bytes,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostRequest) Reset() {
	*x = HostRequest{}
	mi := &file_mmo_v1_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostRequest) ProtoMessage() {}

func (x *HostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_v1_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostRequest.ProtoReflect.Descriptor instead.
func (*HostRequest) Descriptor() ([]byte, []int) {
	return file_mmo_v1_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *HostRequest) GetInstanceId() uint64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *HostRequest) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

type HostReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hosting       bool                   `protobuf:"varint,1,opt,name=hosting,proto3" json:"hosting,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostReply) Reset() {
	*x = HostReply{}
	mi := &file_mmo_v1_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostReply) ProtoMessage() {}

func (x *HostReply) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_v1_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostReply.ProtoReflect.Descriptor instead.
func (*HostReply) Descriptor() ([]byte, []int) {
	return file_mmo_v1_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *HostReply) GetHosting() bool {
	if x != nil {
		return x.Hosting
	}
	return false
}

func (x *HostReply) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HostReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_mmo_v1_cluster_proto protoreflect.FileDescriptor

const file_mmo_v1_cluster_proto_rawDesc = "" +
	"\n" +
	"\x14mmo/v1/cluster.proto\x12\x06mmo.v1\"\x7f\n" +
	"\vBusEnvelope\x12\x19\n" +
	"\breply_to\x18\x01 \x01(\tR\areplyTo\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xd4\x02\n" +
	"\x0fTransferRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\tR\vcharacterId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x15\n" +
	"\x06map_id\x18\x04 \x01(\tR\x05mapId\x12\x1f\n" +
	"\vspawn_point\x18\x05 \x01(\tR\n" +
	"spawnPoint\x12\x1f\n" +
	"\vinstance_id\x18\x06 \x01(\x04R\n" +
	"instanceId\x12\x1f\n" +
	"\vwaypoint_id\x18\f \x01(\tR\n" +
	"waypointId\x12\x14\n" +
	"\x05level\x18\a \x01(\rR\x05level\x12\x10\n" +
	"\x03exp\x18\b \x01(\x03R\x03exp\x12\x12\n" +
	"\x04gold\x18\t \x01(\x03R\x04gold\x12\x14\n" +
	"\x05state\x18\n" +
	" \x01(\fR\x05state\x12\x1f\n" +
	"\vlease_token\x18\v \x01(\x03R\n" +
	"leaseToken\"w\n" +
	"\rTransferReply\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\rR\bentityId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"]\n" +
	"\n" +
	"RoomClosed\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\x04R\n" +
	"instanceId\x12\x15\n" +
	"\x06map_id\x18\x02 \x01(\tR\x05mapId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\"E\n" +
	"\vHostRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\x04R\n" +
	"instanceId\x12\x15\n" +
	"\x06map_id\x18\x02 \x01(\tR\x05mapId\"T\n" +
	"\tHostReply\x12\x18\n" +
	"\ahosting\x18\x01 \x01(\bR\ahosting\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05errorB\x8c\x01\n" +
	"\n" +
	"com.mmo.v1B\fClusterProtoP\x01Z7github.com/ctrl-research/mmo/internal/wire/mmo/v1;mmov1\xa2\x02\x03MXX\xaa\x02\x06Mmo.V1\xca\x02\x06Mmo\\V1\xe2\x02\x12Mmo\\V1\\GPBMetadata\xea\x02\aMmo::V1b\x06proto3"

var (
	file_mmo_v1_cluster_proto_rawDescOnce sync.Once
	file_mmo_v1_cluster_proto_rawDescData []byte
)

func file_mmo_v1_cluster_proto_rawDescGZIP() []byte {
	file_mmo_v1_cluster_proto_rawDescOnce.Do(func() {
		file_mmo_v1_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mmo_v1_cluster_proto_rawDesc), len(file_mmo_v1_cluster_proto_rawDesc)))
	})
	return file_mmo_v1_cluster_proto_rawDescData
}

var file_mmo_v1_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_mmo_v1_cluster_proto_goTypes = []any{
	(*BusEnvelope)(nil),     // 0: mmo.v1.BusEnvelope
	(*TransferRequest)(nil), // 1: mmo.v1.TransferRequest
	(*TransferReply)(nil),   // 2: mmo.v1.TransferReply
	(*RoomClosed)(nil),      // 3: mmo.v1.RoomClosed
	(*HostRequest)(nil),     // 4: mmo.v1.HostRequest
	(*HostReply)(nil),       // 5: mmo.v1.HostReply
}
var file_mmo_v1_cluster_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mmo_v1_cluster_proto_init() }
func file_mmo_v1_cluster_proto_init() {
	if File_mmo_v1_cluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mmo_v1_cluster_proto_rawDesc), len(file_mmo_v1_cluster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mmo_v1_cluster_proto_goTypes,
		DependencyIndexes: file_mmo_v1_cluster_proto_depIdxs,
		MessageInfos:      file_mmo_v1_cluster_proto_msgTypes,
	}.Build()
	File_mmo_v1_cluster_proto = out.File
	file_mmo_v1_cluster_proto_goTypes = nil
	file_mmo_v1_cluster_proto_depIdxs = nil
}
