// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: mmo/v1/game.proto

package mmov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InteractKind int32

const (
	InteractKind_INTERACT_KIND_UNSPECIFIED InteractKind = 0
	InteractKind_INTERACT_KIND_LOOT        InteractKind = 1
)

// Enum value maps for InteractKind.
var (
	InteractKind_name = map[int32]string{
		0: "INTERACT_KIND_UNSPECIFIED",
		1: "INTERACT_KIND_LOOT",
	}
	InteractKind_value = map[string]int32{
		"INTERACT_KIND_UNSPECIFIED": 0,
		"INTERACT_KIND_LOOT":        1,
	}
)

func (x InteractKind) Enum() *InteractKind {
	p := new(InteractKind)
	*p = x
	return p
}

func (x InteractKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InteractKind) Descriptor() protoreflect.EnumDescriptor {
	return file_mmo_v1_game_proto_enumTypes[0].Descriptor()
}

func (InteractKind) Type() protoreflect.EnumType {
	return &file_mmo_v1_game_proto_enumTypes[0]
}

func (x InteractKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InteractKind.Descriptor instead.
func (InteractKind) EnumDescriptor() ([]byte, []int) {
	return file_mmo_v1_game_proto_rawDescGZIP(), []int{0}
}

type EntityKind int32

const (
	EntityKind_ENTITY_KIND_UNSPECIFIED EntityKind = 0
	EntityKind_ENTITY_KIND_PLAYER      EntityKind = 1
	EntityKind_ENTITY_KIND_MOB         EntityKind = 2
	EntityKind_ENTITY_KIND_DROP        EntityKind = 3
	EntityKind_ENTITY_KIND_NPC         EntityKind = 4
)

// Enum value maps for EntityKind.
var (
	EntityKind_name = map[int32]string{
		0: "ENTITY_KIND_UNSPECIFIED",
		1: "ENTITY_KIND_PLAYER",
		2: "ENTITY_KIND_MOB",
		3: "ENTITY_KIND_DROP",
		4: "ENTITY_KIND_NPC",
	}
	EntityKind_value = map[string]int32{
		"ENTITY_KIND_UNSPECIFIED": 0,
		"ENTITY_KIND_PLAYER":      1,
		"ENTITY_KIND_MOB":         2,
		"ENTITY_KIND_DROP":        3,
		"ENTITY_KIND_NPC":         4,
	}
)

func (x EntityKind) Enum() *EntityKind {
	p := new(EntityKind)
	*p = x
	return p
}

func (x EntityKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityKind) Descriptor() protoreflect.EnumDescriptor {
	return file_mmo_v1_game_proto_enumTypes[1].Descriptor()
}

func (EntityKind) Type() protoreflect.EnumType {
	return &file_mmo_v1_game_proto_enumTypes[1]
}

func (x EntityKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityKind.Descriptor instead.
func (EntityKind) EnumDescriptor() ([]byte, []int) {
	return file_mmo_v1_game_proto_rawDescGZIP(), []int{1}
}

// Bit positions in EntityDelta.field_mask.
type EntityField int32

const (
	EntityField_ENTITY_FIELD_UNSPECIFIED EntityField = 0
	EntityField_ENTITY_FIELD_POS         EntityField = 1
	EntityField_ENTITY_FIELD_VEL         EntityField = 2
	EntityField_ENTITY_FIELD_FLAGS       EntityField = 3
	EntityField_ENTITY_FIELD_ANIM        EntityField = 4
	EntityField_ENTITY_FIELD_HP          EntityField = 5
)

// Enum value maps for EntityField.
var (
	EntityField_name = map[int32]string{
		0: "ENTITY_FIELD_UNSPECIFIED",
		1: "ENTITY_FIELD_POS",
		2: "ENTITY_FIELD_VEL",
		3: "ENTITY_FIELD_FLAGS",
		4: "ENTITY_FIELD_ANIM",
		5: "ENTITY_FIELD_HP",
	}
	EntityField_value = map[string]int32{
		"ENTITY_FIELD_UNSPECIFIED": 0,
		"ENTITY_FIELD_POS":         1,
		"ENTITY_FIELD_VEL":         2,
		"ENTITY_FIELD_FLAGS":       3,
		"ENTITY_FIELD_ANIM":        4,
		"ENTITY_FIELD_HP":          5,
	}
)

func (x EntityField) Enum() *EntityField {
	p := new(EntityField)
	*p = x
	return p
}

func (x EntityField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityField) Descriptor() protoreflect.EnumDescriptor {
	return file_mmo_v1_game_proto_enumTypes[2].Descriptor()
}

func (EntityField) Type() protoreflect.EnumType {
	return &file_mmo_v1_game_proto_enumTypes[2]
}

func (x EntityField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityField.Descriptor instead.
func (EntityField) EnumDescriptor() ([]byte, []int) {
	return file_mmo_v1_game_proto_rawDescGZIP(), []int{2}
}

// Bit positions in EntityState.flags and EntityDelta.flags.
type EntityFlag int32

const (
	EntityFlag_ENTITY_FLAG_UNSPECIFIED EntityFlag = 0
	EntityFlag_ENTITY_FLAG_GROUNDED    EntityFlag = 1
	EntityFlag_ENTITY_FLAG_CLIMBING    EntityFlag = 2
	EntityFlag_ENTITY_FLAG_FACING_LEFT EntityFlag = 3
	EntityFlag_ENTITY_FLAG_JUMP_HELD   EntityFlag = 4
)

// Enum value maps for EntityFlag.
var (
	EntityFlag_name = map[int32]string{
		0: "ENTITY_FLAG_UNSPECIFIED",
		1: "ENTITY_FLAG_GROUNDED",
		2: "ENTITY_FLAG_CLIMBING",
		3: "ENTITY_FLAG_FACING_LEFT",
		4: "ENTITY_FLAG_JUMP_HELD",
	}
	EntityFlag_value = map[string]int32{
		"ENTITY_FLAG_UNSPECIFIED": 0,
		"ENTITY_FLAG_GROUNDED":    1,
		"ENTITY_FLAG_CLIMBING":    2,
		"ENTITY_FLAG_FACING_LEFT": 3,
		"ENTITY_FLAG_JUMP_HELD":   4,
	}
)

func (x EntityFlag) Enum() *EntityFlag {
	p := new(EntityFlag)
	*p = x
	return p
}

func (x EntityFlag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityFlag) Descriptor() protoreflect.EnumDescriptor {
	return file_mmo_v1_game_proto_enumTypes[3].Descriptor()
}

func (EntityFlag) Type() protoreflect.EnumType {
	return &file_mmo_v1_game_proto_enumTypes[3]
}

func (x EntityFlag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityFlag.Descriptor instead.
func (EntityFlag) EnumDescriptor() ([]byte, []int) {
	return file_mmo_v1_game_proto_rawDescGZIP(), []int{3}
}

// Envelope is exactly one WebSocket binary frame.
//
// The server batches a whole tick's messages into one envelope rather than
// sending each separately: at 20 Hz with a snapshot plus several events, the
// per-frame WebSocket overhead is otherwise a meaningful share of the traffic.
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        []*ServerMessage       `protobuf:"bytes,1,rep,name=server,proto3" json:"server,omitempty"`
	Client        []*ClientMessage       `protobuf:"bytes,2,rep,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_mmo_v1_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_v1_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_mmo_v1_game_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetServer() []*ServerMessage {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Envelope) GetClient() []*ClientMessage {
	if x != nil {
		return x.Client
	}
	return nil
}

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ClientMessage_Hello
	//	*ClientMessage_Intent
	//	*ClientMessage_Ping
	//	*ClientMessage_Cast
	//	*ClientMessage_Interact
	Body          isClientMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_mmo_v1_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_v1_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_mmo_v1_game_proto_rawDescGZIP(), []int{1}
}

func (x *ClientMessage) GetBody() isClientMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ClientMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Body.(*ClientMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ClientMessage) GetIntent() *Intent {
	if x != nil {
		if x, ok := x.Body.(*ClientMessage_Intent); ok {
			return x.Intent
		}
	}
	return nil
}

func (x *ClientMessage) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Body.(*ClientMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *ClientMessage) GetCast() *Cast {
	if x != nil {
		if x, ok := x.Body.(*ClientMessage_Cast); ok {
			return x.Cast
		}
	}
	return nil
}

func (x *ClientMessage) GetInteract() *Interact {
	if x != nil {
		if x, ok := x.Body.(*ClientMessage_Interact); ok {
			return x.Interact
		}
	}
	return nil
}

type isClientMessage_Body interface {
	isClientMessage_Body()
}

type ClientMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ClientMessage_Intent struct {
	Intent *Intent `protobuf:"bytes,2,opt,name=intent,proto3,oneof"`
}

type ClientMessage_Ping struct {
	Ping *Ping `protobuf:"bytes,3,opt,name=ping,proto3,oneof"`
}

type ClientMessage_Cast struct {
	Cast *Cast `protobuf:"bytes,4,opt,name=cast,proto3,oneof"`
}

type ClientMessage_Interact struct {
	Interact *Interact `protobuf:"bytes,5,opt,name=interact,proto3,oneof"`
}

func (*ClientMessage_Hello) isClientMessage_Body() {}

func (*ClientMessage_Intent) isClientMessage_Body() {}

func (*ClientMessage_Ping) isClientMessage_Body() {}

func (*ClientMessage_Cast) isClientMessage_Body() {}

func (*ClientMessage_Interact) isClientMessage_Body() {}

// Cast requests a skill. The client asks; the server decides.
//
// There is deliberately no field for a target or for damage. The server
// resolves what the cast hits from its own state and rolls the outcome itself,
// so a client can ask to swing but never assert what it connected with.
type Cast struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Seq     uint32                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"` // client sequence, echoed for reconciliation
	SkillId string                 `protobuf:"bytes,2,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	// Facing at the moment of the cast, since a swing resolves in the direction
	// the character is looking rather than at a chosen entity.
	FacingLeft    bool `protobuf:"varint,3,opt,name=facing_left,json=facingLeft,proto3" json:"facing_left,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cast) Reset() {
	*x = Cast{}
	mi := &file_mmo_v1_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cast) ProtoMessage() {}

func (x *Cast) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_v1_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cast.ProtoReflect.Descriptor instead.
func (*Cast) Descriptor() ([]byte, []int) {
	return file_mmo_v1_game_proto_rawDescGZIP(), []int{2}
}

func (x *Cast) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Cast) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

func (x *Cast) GetFacingLeft() bool {
	if x != nil {
		return x.FacingLeft
	}
	return false
}

// Interact is a request to act on a nearby entity: loot a drop, use a portal,
// talk to an NPC.
type Interact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint32                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Kind          InteractKind           `protobuf:"varint,2,opt,name=kind,proto3,enum=mmo.v1.InteractKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Interact) Reset() {
	*x = Interact{}
	mi := &file_mmo_v1_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interact) ProtoMessage() {}

func (x *Interact) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_v1_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interact.ProtoReflect.Descriptor instead.
func (*Interact) Descriptor() ([]byte, []int) {
	return file_mmo_v1_game_proto_rawDescGZIP(), []int{3}
}

func (x *Interact) GetEntityId() uint32 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *Interact) GetKind() InteractKind {
	if x != nil {
		return x.Kind
	}
	return InteractKind_INTERACT_KIND_UNSPECIFIED
}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ServerMessage_Welcome
	//	*ServerMessage_Snapshot
	//	*ServerMessage_Event
	//	*ServerMessage_Pong
	//	*ServerMessage_Kick
	Body          isServerMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_mmo_v1_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_v1_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_mmo_v1_game_proto_rawDescGZIP(), []int{4}
}

func (x *ServerMessage) GetBody() isServerMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ServerMessage) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *ServerMessage) GetSnapshot() *Snapshot {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *ServerMessage) GetEvent() *Event {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *ServerMessage) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *ServerMessage) GetKick() *Kick {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_Kick); ok {
			return x.Kick
		}
	}
	return nil
}

type isServerMessage_Body interface {
	isServerMessage_Body()
}

type ServerMessage_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,1,opt,name=welcome,proto3,oneof"`
}

type ServerMessage_Snapshot struct {
	Snapshot *Snapshot `protobuf:"bytes,2,opt,name=snapshot,proto3,oneof"`
}

type ServerMessage_Event struct {
	Event *Event `protobuf:"bytes,3,opt,name=event,proto3,oneof"`
}

type ServerMessage_Pong struct {
	Pong *Pong `protobuf:"bytes,4,opt,name=pong,proto3,oneof"`
}

type ServerMessage_Kick struct {
	Kick *Kick `protobuf:"bytes,5,opt,name=kick,proto3,oneof"`
}

func (*ServerMessage_Welcome) isServerMessage_Body() {}

func (*ServerMessage_Snapshot) isServerMessage_Body() {}

func (*ServerMessage_Event) isServerMessage_Body() {}

func (*ServerMessage_Pong) isServerMessage_Body() {}

func (*ServerMessage_Kick) isServerMessage_Body() {}

// Hello is the first message on a new connection.
type Hello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Single-use ticket obtained over authenticated HTTP, valid for 30 seconds.
	// Credentials never appear in the WebSocket URL, where they would leak into
	// proxy logs and browser history.
	Ticket string `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	// Both sides must agree on the protocol shape and on the content that
	// describes the world, or the resulting bugs are nearly unreadable.
	ProtocolVersion uint32 `protobuf:"varint,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	ContentHash     string `protobuf:"bytes,3,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_mmo_v1_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_v1_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_mmo_v1_game_proto_rawDescGZIP(), []int{5}
}

func (x *Hello) GetTicket() string {
	if x != nil {
		return x.Ticket
	}
	return ""
}

func (x *Hello) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Hello) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

type Welcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint32                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // the player's own entity, to distinguish self
	InstanceId    uint64                 `protobuf:"varint,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Tick          uint64                 `protobuf:"varint,3,opt,name=tick,proto3" json:"tick,omitempty"`                   // server tick at the moment of joining
	TickMs        uint32                 `protobuf:"varint,4,opt,name=tick_ms,json=tickMs,proto3" json:"tick_ms,omitempty"` // simulation period, so the client need not assume
	MapId         string                 `protobuf:"bytes,5,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	Self          *EntityState           `protobuf:"bytes,6,opt,name=self,proto3" json:"self,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_mmo_v1_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_v1_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_mmo_v1_game_proto_rawDescGZIP(), []int{6}
}

func (x *Welcome) GetEntityId() uint32 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *Welcome) GetInstanceId() uint64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *Welcome) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *Welcome) GetTickMs() uint32 {
	if x != nil {
		return x.TickMs
	}
	return 0
}

func (x *Welcome) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *Welcome) GetSelf() *EntityState {
	if x != nil {
		return x.Self
	}
	return nil
}

// Kick closes the connection with a reason the client can act on. The code
// mirrors the WebSocket close code; see docs/protocol.md for the table.
type Kick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kick) Reset() {
	*x = Kick{}
	mi := &file_mmo_v1_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kick) ProtoMessage() {}

func (x *Kick) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_v1_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kick.ProtoReflect.Descriptor instead.
func (*Kick) Descriptor() ([]byte, []int) {
	return file_mmo_v1_game_proto_rawDescGZIP(), []int{7}
}

func (x *Kick) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Kick) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Intent is what buttons the player is holding. It carries no position: the
// server derives where the player is, which is what makes teleport and speed
// hacks unrepresentable rather than merely detectable.
type Intent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Strictly increasing per connection. Echoed back as Snapshot.ack_seq to
	// drive client reconciliation. A sequence number needs no clock sync, and a
	// client that lies about it only corrupts its own prediction.
	Seq uint32 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	// Highest snapshot tick this client has received, used as the delta
	// baseline. Riding on Intent means acknowledgements cost no extra messages.
	AckSnapshot uint64 `protobuf:"varint,2,opt,name=ack_snapshot,json=ackSnapshot,proto3" json:"ack_snapshot,omitempty"`
	// Horizontal intent in thousandths, clamped server-side to [-1000, 1000].
	MoveX         int32 `protobuf:"zigzag32,3,opt,name=move_x,json=moveX,proto3" json:"move_x,omitempty"`
	Jump          bool  `protobuf:"varint,4,opt,name=jump,proto3" json:"jump,omitempty"`
	Up            bool  `protobuf:"varint,5,opt,name=up,proto3" json:"up,omitempty"`
	Down          bool  `protobuf:"varint,6,opt,name=down,proto3" json:"down,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Intent) Reset() {
	*x = Intent{}
	mi := &file_mmo_v1_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Intent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Intent) ProtoMessage() {}

func (x *Intent) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_v1_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Intent.ProtoReflect.Descriptor instead.
func (*Intent) Descriptor() ([]byte, []int) {
	return file_mmo_v1_game_proto_rawDescGZIP(), []int{8}
}

func (x *Intent) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Intent) GetAckSnapshot() uint64 {
	if x != nil {
		return x.AckSnapshot
	}
	return 0
}

func (x *Intent) GetMoveX() int32 {
	if x != nil {
		return x.MoveX
	}
	return 0
}

func (x *Intent) GetJump() bool {
	if x != nil {
		return x.Jump
	}
	return false
}

func (x *Intent) GetUp() bool {
	if x != nil {
		return x.Up
	}
	return false
}

func (x *Intent) GetDown() bool {
	if x != nil {
		return x.Down
	}
	return false
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientTimeMs  uint64                 `protobuf:"varint,1,opt,name=client_time_ms,json=clientTimeMs,proto3" json:"client_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_mmo_v1_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_v1_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_mmo_v1_game_proto_rawDescGZIP(), []int{9}
}

func (x *Ping) GetClientTimeMs() uint64 {
	if x != nil {
		return x.ClientTimeMs
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientTimeMs  uint64                 `protobuf:"varint,1,opt,name=client_time_ms,json=clientTimeMs,proto3" json:"client_time_ms,omitempty"` // echoed, so the client can compute RTT
	ServerTick    uint64                 `protobuf:"varint,2,opt,name=server_tick,json=serverTick,proto3" json:"server_tick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_mmo_v1_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_v1_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_mmo_v1_game_proto_rawDescGZIP(), []int{10}
}

func (x *Pong) GetClientTimeMs() uint64 {
	if x != nil {
		return x.ClientTimeMs
	}
	return 0
}

func (x *Pong) GetServerTick() uint64 {
	if x != nil {
		return x.ServerTick
	}
	return 0
}

// EntityState is a complete entity, sent when it first becomes visible and
// whenever a full snapshot is due.
//
// Positions and velocities are raw Q24.8 fixed-point, the same representation
// the simulation uses internally, so serialisation neither rounds nor converts.
// Floating point appears nowhere in the movement path.
type EntityState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind  EntityKind             `protobuf:"varint,2,opt,name=kind,proto3,enum=mmo.v1.EntityKind" json:"kind,omitempty"`
	// Visibility layer. 0 is the shared layer, seen by everyone in the room; any
	// other value is a per-player or per-party layer. Players are always
	// shared-layer. See docs/architecture.md.
	Layer uint32 `protobuf:"varint,3,opt,name=layer,proto3" json:"layer,omitempty"`
	X     int32  `protobuf:"zigzag32,4,opt,name=x,proto3" json:"x,omitempty"`
	Y     int32  `protobuf:"zigzag32,5,opt,name=y,proto3" json:"y,omitempty"`
	Vx    int32  `protobuf:"zigzag32,6,opt,name=vx,proto3" json:"vx,omitempty"`
	Vy    int32  `protobuf:"zigzag32,7,opt,name=vy,proto3" json:"vy,omitempty"`
	W     int32  `protobuf:"zigzag32,8,opt,name=w,proto3" json:"w,omitempty"`
	H     int32  `protobuf:"zigzag32,9,opt,name=h,proto3" json:"h,omitempty"`
	Flags uint32 `protobuf:"varint,10,opt,name=flags,proto3" json:"flags,omitempty"` // bitfield of EntityFlag
	Anim  uint32 `protobuf:"varint,11,opt,name=anim,proto3" json:"anim,omitempty"`
	Hp    uint32 `protobuf:"varint,12,opt,name=hp,proto3" json:"hp,omitempty"`
	HpMax uint32 `protobuf:"varint,13,opt,name=hp_max,json=hpMax,proto3" json:"hp_max,omitempty"`
	Name  string `protobuf:"bytes,14,opt,name=name,proto3" json:"name,omitempty"`
	// State the player's own entity needs for prediction but other entities do
	// not. Only ever populated for self. Omitting any of it would make the
	// client's replay diverge from the server.
	Coyote      uint32 `protobuf:"varint,15,opt,name=coyote,proto3" json:"coyote,omitempty"`
	JumpBuffer  uint32 `protobuf:"varint,16,opt,name=jump_buffer,json=jumpBuffer,proto3" json:"jump_buffer,omitempty"`
	DropThrough uint32 `protobuf:"varint,17,opt,name=drop_through,json=dropThrough,proto3" json:"drop_through,omitempty"`
	// Progression, only populated for self.
	Level     uint32 `protobuf:"varint,18,opt,name=level,proto3" json:"level,omitempty"`
	Exp       uint64 `protobuf:"varint,19,opt,name=exp,proto3" json:"exp,omitempty"`
	ExpToNext uint64 `protobuf:"varint,20,opt,name=exp_to_next,json=expToNext,proto3" json:"exp_to_next,omitempty"`
	Mp        uint32 `protobuf:"varint,21,opt,name=mp,proto3" json:"mp,omitempty"`
	MpMax     uint32 `protobuf:"varint,22,opt,name=mp_max,json=mpMax,proto3" json:"mp_max,omitempty"`
	// Ground drops. A drop is an entity like any other so that visibility,
	// layering, and removal all work without a special case -- which is also
	// what makes cross-layer looting unrepresentable rather than merely
	// forbidden.
	DropItem string `protobuf:"bytes,23,opt,name=drop_item,json=dropItem,proto3" json:"drop_item,omitempty"`
	DropQty  uint32 `protobuf:"varint,24,opt,name=drop_qty,json=dropQty,proto3" json:"drop_qty,omitempty"`
	DropGold uint32 `protobuf:"varint,25,opt,name=drop_gold,json=dropGold,proto3" json:"drop_gold,omitempty"`
	// Content id of a mob, so the client can pick its sprite without the server
	// sending a name string every time one spawns.
	MobId         string `protobuf:"bytes,26,opt,name=mob_id,json=mobId,proto3" json:"mob_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityState) Reset() {
	*x = EntityState{}
	mi := &file_mmo_v1_game_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityState) ProtoMessage() {}

func (x *EntityState) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_v1_game_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityState.ProtoReflect.Descriptor instead.
func (*EntityState) Descriptor() ([]byte, []int) {
	return file_mmo_v1_game_proto_rawDescGZIP(), []int{11}
}

func (x *EntityState) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EntityState) GetKind() EntityKind {
	if x != nil {
		return x.Kind
	}
	return EntityKind_ENTITY_KIND_UNSPECIFIED
}

func (x *EntityState) GetLayer() uint32 {
	if x != nil {
		return x.Layer
	}
	return 0
}

func (x *EntityState) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *EntityState) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *EntityState) GetVx() int32 {
	if x != nil {
		return x.Vx
	}
	return 0
}

func (x *EntityState) GetVy() int32 {
	if x != nil {
		return x.Vy
	}
	return 0
}

func (x *EntityState) GetW() int32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *EntityState) GetH() int32 {
	if x != nil {
		return x.H
	}
	return 0
}

func (x *EntityState) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *EntityState) GetAnim() uint32 {
	if x != nil {
		return x.Anim
	}
	return 0
}

func (x *EntityState) GetHp() uint32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *EntityState) GetHpMax() uint32 {
	if x != nil {
		return x.HpMax
	}
	return 0
}

func (x *EntityState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EntityState) GetCoyote() uint32 {
	if x != nil {
		return x.Coyote
	}
	return 0
}

func (x *EntityState) GetJumpBuffer() uint32 {
	if x != nil {
		return x.JumpBuffer
	}
	return 0
}

func (x *EntityState) GetDropThrough() uint32 {
	if x != nil {
		return x.DropThrough
	}
	return 0
}

func (x *EntityState) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *EntityState) GetExp() uint64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *EntityState) GetExpToNext() uint64 {
	if x != nil {
		return x.ExpToNext
	}
	return 0
}

func (x *EntityState) GetMp() uint32 {
	if x != nil {
		return x.Mp
	}
	return 0
}

func (x *EntityState) GetMpMax() uint32 {
	if x != nil {
		return x.MpMax
	}
	return 0
}

func (x *EntityState) GetDropItem() string {
	if x != nil {
		return x.DropItem
	}
	return ""
}

func (x *EntityState) GetDropQty() uint32 {
	if x != nil {
		return x.DropQty
	}
	return 0
}

func (x *EntityState) GetDropGold() uint32 {
	if x != nil {
		return x.DropGold
	}
	return 0
}

func (x *EntityState) GetMobId() string {
	if x != nil {
		return x.MobId
	}
	return ""
}

// EntityDelta carries only what changed since the baseline tick.
type EntityDelta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Bitfield of EntityField marking which of the fields below are present.
	FieldMask     uint32 `protobuf:"varint,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	X             int32  `protobuf:"zigzag32,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32  `protobuf:"zigzag32,4,opt,name=y,proto3" json:"y,omitempty"`
	Vx            int32  `protobuf:"zigzag32,5,opt,name=vx,proto3" json:"vx,omitempty"`
	Vy            int32  `protobuf:"zigzag32,6,opt,name=vy,proto3" json:"vy,omitempty"`
	Flags         uint32 `protobuf:"varint,7,opt,name=flags,proto3" json:"flags,omitempty"`
	Anim          uint32 `protobuf:"varint,8,opt,name=anim,proto3" json:"anim,omitempty"`
	Hp            uint32 `protobuf:"varint,9,opt,name=hp,proto3" json:"hp,omitempty"`
	HpMax         uint32 `protobuf:"varint,10,opt,name=hp_max,json=hpMax,proto3" json:"hp_max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityDelta) Reset() {
	*x = EntityDelta{}
	mi := &file_mmo_v1_game_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityDelta) ProtoMessage() {}

func (x *EntityDelta) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_v1_game_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityDelta.ProtoReflect.Descriptor instead.
func (*EntityDelta) Descriptor() ([]byte, []int) {
	return file_mmo_v1_game_proto_rawDescGZIP(), []int{12}
}

func (x *EntityDelta) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EntityDelta) GetFieldMask() uint32 {
	if x != nil {
		return x.FieldMask
	}
	return 0
}

func (x *EntityDelta) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *EntityDelta) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *EntityDelta) GetVx() int32 {
	if x != nil {
		return x.Vx
	}
	return 0
}

func (x *EntityDelta) GetVy() int32 {
	if x != nil {
		return x.Vy
	}
	return 0
}

func (x *EntityDelta) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *EntityDelta) GetAnim() uint32 {
	if x != nil {
		return x.Anim
	}
	return 0
}

func (x *EntityDelta) GetHp() uint32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *EntityDelta) GetHpMax() uint32 {
	if x != nil {
		return x.HpMax
	}
	return 0
}

type Snapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Tick  uint64                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	// Tick this delta is relative to. Zero means a full snapshot: either the
	// first one, or one sent because the client's baseline grew too stale to be
	// worth chasing.
	BaselineTick uint64 `protobuf:"varint,2,opt,name=baseline_tick,json=baselineTick,proto3" json:"baseline_tick,omitempty"`
	// Highest Intent.seq applied by the server. The client discards
	// acknowledged inputs and replays the rest on top of authoritative state.
	AckSeq   uint32         `protobuf:"varint,3,opt,name=ack_seq,json=ackSeq,proto3" json:"ack_seq,omitempty"`
	Entities []*EntityDelta `protobuf:"bytes,4,rep,name=entities,proto3" json:"entities,omitempty"`
	Entered  []*EntityState `protobuf:"bytes,5,rep,name=entered,proto3" json:"entered,omitempty"`         // newly visible, sent in full
	Removed  []uint32       `protobuf:"varint,6,rep,packed,name=removed,proto3" json:"removed,omitempty"` // died, or left the viewer's layer/range
	// The player's own entity, always complete and never delta-compressed. It is
	// one entity, it is what reconciliation is measured against, and a delta bug
	// here is far more expensive than the handful of bytes it would save.
	Self          *EntityState `protobuf:"bytes,7,opt,name=self,proto3" json:"self,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_mmo_v1_game_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_v1_game_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_mmo_v1_game_proto_rawDescGZIP(), []int{13}
}

func (x *Snapshot) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *Snapshot) GetBaselineTick() uint64 {
	if x != nil {
		return x.BaselineTick
	}
	return 0
}

func (x *Snapshot) GetAckSeq() uint32 {
	if x != nil {
		return x.AckSeq
	}
	return 0
}

func (x *Snapshot) GetEntities() []*EntityDelta {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *Snapshot) GetEntered() []*EntityState {
	if x != nil {
		return x.Entered
	}
	return nil
}

func (x *Snapshot) GetRemoved() []uint32 {
	if x != nil {
		return x.Removed
	}
	return nil
}

func (x *Snapshot) GetSelf() *EntityState {
	if x != nil {
		return x.Self
	}
	return nil
}

// Event is a one-shot fact rather than state: never delta-compressed, and
// never inferred by the client from state changes. A client that derives "took
// damage" from a falling HP number cannot tell 200 damage from two hits of 100.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*Event_PlayerJoined
	//	*Event_PlayerLeft
	//	*Event_Damage
	//	*Event_Died
	//	*Event_SkillCast
	//	*Event_ExpGained
	//	*Event_LevelUp
	//	*Event_LootTaken
	Body          isEvent_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_mmo_v1_game_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_v1_game_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_mmo_v1_game_proto_rawDescGZIP(), []int{14}
}

func (x *Event) GetBody() isEvent_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Event) GetPlayerJoined() *PlayerJoined {
	if x != nil {
		if x, ok := x.Body.(*Event_PlayerJoined); ok {
			return x.PlayerJoined
		}
	}
	return nil
}

func (x *Event) GetPlayerLeft() *PlayerLeft {
	if x != nil {
		if x, ok := x.Body.(*Event_PlayerLeft); ok {
			return x.PlayerLeft
		}
	}
	return nil
}

func (x *Event) GetDamage() *DamageDealt {
	if x != nil {
		if x, ok := x.Body.(*Event_Damage); ok {
			return x.Damage
		}
	}
	return nil
}

func (x *Event) GetDied() *EntityDied {
	if x != nil {
		if x, ok := x.Body.(*Event_Died); ok {
			return x.Died
		}
	}
	return nil
}

func (x *Event) GetSkillCast() *SkillCast {
	if x != nil {
		if x, ok := x.Body.(*Event_SkillCast); ok {
			return x.SkillCast
		}
	}
	return nil
}

func (x *Event) GetExpGained() *ExpGained {
	if x != nil {
		if x, ok := x.Body.(*Event_ExpGained); ok {
			return x.ExpGained
		}
	}
	return nil
}

func (x *Event) GetLevelUp() *LevelUp {
	if x != nil {
		if x, ok := x.Body.(*Event_LevelUp); ok {
			return x.LevelUp
		}
	}
	return nil
}

func (x *Event) GetLootTaken() *LootTaken {
	if x != nil {
		if x, ok := x.Body.(*Event_LootTaken); ok {
			return x.LootTaken
		}
	}
	return nil
}

type isEvent_Body interface {
	isEvent_Body()
}

type Event_PlayerJoined struct {
	PlayerJoined *PlayerJoined `protobuf:"bytes,1,opt,name=player_joined,json=playerJoined,proto3,oneof"`
}

type Event_PlayerLeft struct {
	PlayerLeft *PlayerLeft `protobuf:"bytes,2,opt,name=player_left,json=playerLeft,proto3,oneof"`
}

type Event_Damage struct {
	Damage *DamageDealt `protobuf:"bytes,3,opt,name=damage,proto3,oneof"`
}

type Event_Died struct {
	Died *EntityDied `protobuf:"bytes,4,opt,name=died,proto3,oneof"`
}

type Event_SkillCast struct {
	SkillCast *SkillCast `protobuf:"bytes,5,opt,name=skill_cast,json=skillCast,proto3,oneof"`
}

type Event_ExpGained struct {
	ExpGained *ExpGained `protobuf:"bytes,6,opt,name=exp_gained,json=expGained,proto3,oneof"`
}

type Event_LevelUp struct {
	LevelUp *LevelUp `protobuf:"bytes,7,opt,name=level_up,json=levelUp,proto3,oneof"`
}

type Event_LootTaken struct {
	LootTaken *LootTaken `protobuf:"bytes,8,opt,name=loot_taken,json=lootTaken,proto3,oneof"`
}

func (*Event_PlayerJoined) isEvent_Body() {}

func (*Event_PlayerLeft) isEvent_Body() {}

func (*Event_Damage) isEvent_Body() {}

func (*Event_Died) isEvent_Body() {}

func (*Event_SkillCast) isEvent_Body() {}

func (*Event_ExpGained) isEvent_Body() {}

func (*Event_LevelUp) isEvent_Body() {}

func (*Event_LootTaken) isEvent_Body() {}

// DamageDealt is sent rather than inferred from a falling HP number, because a
// client deriving "took damage" from state cannot tell 200 damage from two
// hits of 100 -- and the difference is the whole feel of a fight.
type DamageDealt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      uint32                 `protobuf:"varint,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	TargetId      uint32                 `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Amount        uint32                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Critical      bool                   `protobuf:"varint,4,opt,name=critical,proto3" json:"critical,omitempty"`
	Element       string                 `protobuf:"bytes,5,opt,name=element,proto3" json:"element,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DamageDealt) Reset() {
	*x = DamageDealt{}
	mi := &file_mmo_v1_game_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DamageDealt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DamageDealt) ProtoMessage() {}

func (x *DamageDealt) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_v1_game_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DamageDealt.ProtoReflect.Descriptor instead.
func (*DamageDealt) Descriptor() ([]byte, []int) {
	return file_mmo_v1_game_proto_rawDescGZIP(), []int{15}
}

func (x *DamageDealt) GetSourceId() uint32 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

func (x *DamageDealt) GetTargetId() uint32 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *DamageDealt) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DamageDealt) GetCritical() bool {
	if x != nil {
		return x.Critical
	}
	return false
}

func (x *DamageDealt) GetElement() string {
	if x != nil {
		return x.Element
	}
	return ""
}

type EntityDied struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint32                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	KillerId      uint32                 `protobuf:"varint,2,opt,name=killer_id,json=killerId,proto3" json:"killer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityDied) Reset() {
	*x = EntityDied{}
	mi := &file_mmo_v1_game_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityDied) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityDied) ProtoMessage() {}

func (x *EntityDied) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_v1_game_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityDied.ProtoReflect.Descriptor instead.
func (*EntityDied) Descriptor() ([]byte, []int) {
	return file_mmo_v1_game_proto_rawDescGZIP(), []int{16}
}

func (x *EntityDied) GetEntityId() uint32 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *EntityDied) GetKillerId() uint32 {
	if x != nil {
		return x.KillerId
	}
	return 0
}

type SkillCast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CasterId      uint32                 `protobuf:"varint,1,opt,name=caster_id,json=casterId,proto3" json:"caster_id,omitempty"`
	SkillId       string                 `protobuf:"bytes,2,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	FacingLeft    bool                   `protobuf:"varint,3,opt,name=facing_left,json=facingLeft,proto3" json:"facing_left,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillCast) Reset() {
	*x = SkillCast{}
	mi := &file_mmo_v1_game_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillCast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillCast) ProtoMessage() {}

func (x *SkillCast) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_v1_game_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillCast.ProtoReflect.Descriptor instead.
func (*SkillCast) Descriptor() ([]byte, []int) {
	return file_mmo_v1_game_proto_rawDescGZIP(), []int{17}
}

func (x *SkillCast) GetCasterId() uint32 {
	if x != nil {
		return x.CasterId
	}
	return 0
}

func (x *SkillCast) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

func (x *SkillCast) GetFacingLeft() bool {
	if x != nil {
		return x.FacingLeft
	}
	return false
}

type ExpGained struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        uint64                 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Total         uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpGained) Reset() {
	*x = ExpGained{}
	mi := &file_mmo_v1_game_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpGained) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpGained) ProtoMessage() {}

func (x *ExpGained) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_v1_game_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpGained.ProtoReflect.Descriptor instead.
func (*ExpGained) Descriptor() ([]byte, []int) {
	return file_mmo_v1_game_proto_rawDescGZIP(), []int{18}
}

func (x *ExpGained) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ExpGained) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type LevelUp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         uint32                 `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	ExpToNext     uint64                 `protobuf:"varint,2,opt,name=exp_to_next,json=expToNext,proto3" json:"exp_to_next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LevelUp) Reset() {
	*x = LevelUp{}
	mi := &file_mmo_v1_game_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LevelUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LevelUp) ProtoMessage() {}

func (x *LevelUp) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_v1_game_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LevelUp.ProtoReflect.Descriptor instead.
func (*LevelUp) Descriptor() ([]byte, []int) {
	return file_mmo_v1_game_proto_rawDescGZIP(), []int{19}
}

func (x *LevelUp) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *LevelUp) GetExpToNext() uint64 {
	if x != nil {
		return x.ExpToNext
	}
	return 0
}

type LootTaken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint32                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Qty           uint32                 `protobuf:"varint,3,opt,name=qty,proto3" json:"qty,omitempty"`
	Gold          uint32                 `protobuf:"varint,4,opt,name=gold,proto3" json:"gold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LootTaken) Reset() {
	*x = LootTaken{}
	mi := &file_mmo_v1_game_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LootTaken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LootTaken) ProtoMessage() {}

func (x *LootTaken) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_v1_game_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LootTaken.ProtoReflect.Descriptor instead.
func (*LootTaken) Descriptor() ([]byte, []int) {
	return file_mmo_v1_game_proto_rawDescGZIP(), []int{20}
}

func (x *LootTaken) GetEntityId() uint32 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *LootTaken) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *LootTaken) GetQty() uint32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *LootTaken) GetGold() uint32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

type PlayerJoined struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint32                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerJoined) Reset() {
	*x = PlayerJoined{}
	mi := &file_mmo_v1_game_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerJoined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerJoined) ProtoMessage() {}

func (x *PlayerJoined) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_v1_game_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerJoined.ProtoReflect.Descriptor instead.
func (*PlayerJoined) Descriptor() ([]byte, []int) {
	return file_mmo_v1_game_proto_rawDescGZIP(), []int{21}
}

func (x *PlayerJoined) GetEntityId() uint32 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *PlayerJoined) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PlayerLeft struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint32                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLeft) Reset() {
	*x = PlayerLeft{}
	mi := &file_mmo_v1_game_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLeft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLeft) ProtoMessage() {}

func (x *PlayerLeft) ProtoReflect() protoreflect.Message {
	mi := &file_mmo_v1_game_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLeft.ProtoReflect.Descriptor instead.
func (*PlayerLeft) Descriptor() ([]byte, []int) {
	return file_mmo_v1_game_proto_rawDescGZIP(), []int{22}
}

func (x *PlayerLeft) GetEntityId() uint32 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

var File_mmo_v1_game_proto protoreflect.FileDescriptor

const file_mmo_v1_game_proto_rawDesc = "" +
	"\n" +
	"\x11mmo/v1/game.proto\x12\x06mmo.v1\"h\n" +
	"\bEnvelope\x12-\n" +
	"\x06server\x18\x01 \x03(\v2\x15.mmo.v1.ServerMessageR\x06server\x12-\n" +
	"\x06client\x18\x02 \x03(\v2\x15.mmo.v1.ClientMessageR\x06client\"\xe6\x01\n" +
	"\rClientMessage\x12%\n" +
	"\x05hello\x18\x01 \x01(\v2\r.mmo.v1.HelloH\x00R\x05hello\x12(\n" +
	"\x06intent\x18\x02 \x01(\v2\x0e.mmo.v1.IntentH\x00R\x06intent\x12\"\n" +
	"\x04ping\x18\x03 \x01(\v2\f.mmo.v1.PingH\x00R\x04ping\x12\"\n" +
	"\x04cast\x18\x04 \x01(\v2\f.mmo.v1.CastH\x00R\x04cast\x12.\n" +
	"\binteract\x18\x05 \x01(\v2\x10.mmo.v1.InteractH\x00R\binteractB\x06\n" +
	"\x04bodyJ\x04\b\x06\x10\n" +
	"\"T\n" +
	"\x04Cast\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\rR\x03seq\x12\x19\n" +
	"\bskill_id\x18\x02 \x01(\tR\askillId\x12\x1f\n" +
	"\vfacing_left\x18\x03 \x01(\bR\n" +
	"facingLeft\"Q\n" +
	"\bInteract\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\rR\bentityId\x12(\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x14.mmo.v1.InteractKindR\x04kind\"\xe9\x01\n" +
	"\rServerMessage\x12+\n" +
	"\awelcome\x18\x01 \x01(\v2\x0f.mmo.v1.WelcomeH\x00R\awelcome\x12.\n" +
	"\bsnapshot\x18\x02 \x01(\v2\x10.mmo.v1.SnapshotH\x00R\bsnapshot\x12%\n" +
	"\x05event\x18\x03 \x01(\v2\r.mmo.v1.EventH\x00R\x05event\x12\"\n" +
	"\x04pong\x18\x04 \x01(\v2\f.mmo.v1.PongH\x00R\x04pong\x12\"\n" +
	"\x04kick\x18\x05 \x01(\v2\f.mmo.v1.KickH\x00R\x04kickB\x06\n" +
	"\x04bodyJ\x04\b\x06\x10\n" +
	"\"m\n" +
	"\x05Hello\x12\x16\n" +
	"\x06ticket\x18\x01 \x01(\tR\x06ticket\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\rR\x0fprotocolVersion\x12!\n" +
	"\fcontent_hash\x18\x03 \x01(\tR\vcontentHash\"\xb4\x01\n" +
	"\aWelcome\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\rR\bentityId\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\x04R\n" +
	"instanceId\x12\x12\n" +
	"\x04tick\x18\x03 \x01(\x04R\x04tick\x12\x17\n" +
	"\atick_ms\x18\x04 \x01(\rR\x06tickMs\x12\x15\n" +
	"\x06map_id\x18\x05 \x01(\tR\x05mapId\x12'\n" +
	"\x04self\x18\x06 \x01(\v2\x13.mmo.v1.EntityStateR\x04self\"2\n" +
	"\x04Kick\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x8c\x01\n" +
	"\x06Intent\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\rR\x03seq\x12!\n" +
	"\fack_snapshot\x18\x02 \x01(\x04R\vackSnapshot\x12\x15\n" +
	"\x06move_x\x18\x03 \x01(\x11R\x05moveX\x12\x12\n" +
	"\x04jump\x18\x04 \x01(\bR\x04jump\x12\x0e\n" +
	"\x02up\x18\x05 \x01(\bR\x02up\x12\x12\n" +
	"\x04down\x18\x06 \x01(\bR\x04down\",\n" +
	"\x04Ping\x12$\n" +
	"\x0eclient_time_ms\x18\x01 \x01(\x04R\fclientTimeMs\"M\n" +
	"\x04Pong\x12$\n" +
	"\x0eclient_time_ms\x18\x01 \x01(\x04R\fclientTimeMs\x12\x1f\n" +
	"\vserver_tick\x18\x02 \x01(\x04R\n" +
	"serverTick\"\xcf\x04\n" +
	"\vEntityState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12&\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x12.mmo.v1.EntityKindR\x04kind\x12\x14\n" +
	"\x05layer\x18\x03 \x01(\rR\x05layer\x12\f\n" +
	"\x01x\x18\x04 \x01(\x11R\x01x\x12\f\n" +
	"\x01y\x18\x05 \x01(\x11R\x01y\x12\x0e\n" +
	"\x02vx\x18\x06 \x01(\x11R\x02vx\x12\x0e\n" +
	"\x02vy\x18\a \x01(\x11R\x02vy\x12\f\n" +
	"\x01w\x18\b \x01(\x11R\x01w\x12\f\n" +
	"\x01h\x18\t \x01(\x11R\x01h\x12\x14\n" +
	"\x05flags\x18\n" +
	" \x01(\rR\x05flags\x12\x12\n" +
	"\x04anim\x18\v \x01(\rR\x04anim\x12\x0e\n" +
	"\x02hp\x18\f \x01(\rR\x02hp\x12\x15\n" +
	"\x06hp_max\x18\r \x01(\rR\x05hpMax\x12\x12\n" +
	"\x04name\x18\x0e \x01(\tR\x04name\x12\x16\n" +
	"\x06coyote\x18\x0f \x01(\rR\x06coyote\x12\x1f\n" +
	"\vjump_buffer\x18\x10 \x01(\rR\n" +
	"jumpBuffer\x12!\n" +
	"\fdrop_through\x18\x11 \x01(\rR\vdropThrough\x12\x14\n" +
	"\x05level\x18\x12 \x01(\rR\x05level\x12\x10\n" +
	"\x03exp\x18\x13 \x01(\x04R\x03exp\x12\x1e\n" +
	"\vexp_to_next\x18\x14 \x01(\x04R\texpToNext\x12\x0e\n" +
	"\x02mp\x18\x15 \x01(\rR\x02mp\x12\x15\n" +
	"\x06mp_max\x18\x16 \x01(\rR\x05mpMax\x12\x1b\n" +
	"\tdrop_item\x18\x17 \x01(\tR\bdropItem\x12\x19\n" +
	"\bdrop_qty\x18\x18 \x01(\rR\adropQty\x12\x1b\n" +
	"\tdrop_gold\x18\x19 \x01(\rR\bdropGold\x12\x15\n" +
	"\x06mob_id\x18\x1a \x01(\tR\x05mobId\"\xc9\x01\n" +
	"\vEntityDelta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"field_mask\x18\x02 \x01(\rR\tfieldMask\x12\f\n" +
	"\x01x\x18\x03 \x01(\x11R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x11R\x01y\x12\x0e\n" +
	"\x02vx\x18\x05 \x01(\x11R\x02vx\x12\x0e\n" +
	"\x02vy\x18\x06 \x01(\x11R\x02vy\x12\x14\n" +
	"\x05flags\x18\a \x01(\rR\x05flags\x12\x12\n" +
	"\x04anim\x18\b \x01(\rR\x04anim\x12\x0e\n" +
	"\x02hp\x18\t \x01(\rR\x02hp\x12\x15\n" +
	"\x06hp_max\x18\n" +
	" \x01(\rR\x05hpMax\"\xff\x01\n" +
	"\bSnapshot\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x04R\x04tick\x12#\n" +
	"\rbaseline_tick\x18\x02 \x01(\x04R\fbaselineTick\x12\x17\n" +
	"\aack_seq\x18\x03 \x01(\rR\x06ackSeq\x12/\n" +
	"\bentities\x18\x04 \x03(\v2\x13.mmo.v1.EntityDeltaR\bentities\x12-\n" +
	"\aentered\x18\x05 \x03(\v2\x13.mmo.v1.EntityStateR\aentered\x12\x18\n" +
	"\aremoved\x18\x06 \x03(\rR\aremoved\x12'\n" +
	"\x04self\x18\a \x01(\v2\x13.mmo.v1.EntityStateR\x04self\"\xac\x03\n" +
	"\x05Event\x12;\n" +
	"\rplayer_joined\x18\x01 \x01(\v2\x14.mmo.v1.PlayerJoinedH\x00R\fplayerJoined\x125\n" +
	"\vplayer_left\x18\x02 \x01(\v2\x12.mmo.v1.PlayerLeftH\x00R\n" +
	"playerLeft\x12-\n" +
	"\x06damage\x18\x03 \x01(\v2\x13.mmo.v1.DamageDealtH\x00R\x06damage\x12(\n" +
	"\x04died\x18\x04 \x01(\v2\x12.mmo.v1.EntityDiedH\x00R\x04died\x122\n" +
	"\n" +
	"skill_cast\x18\x05 \x01(\v2\x11.mmo.v1.SkillCastH\x00R\tskillCast\x122\n" +
	"\n" +
	"exp_gained\x18\x06 \x01(\v2\x11.mmo.v1.ExpGainedH\x00R\texpGained\x12,\n" +
	"\blevel_up\x18\a \x01(\v2\x0f.mmo.v1.LevelUpH\x00R\alevelUp\x122\n" +
	"\n" +
	"loot_taken\x18\b \x01(\v2\x11.mmo.v1.LootTakenH\x00R\tlootTakenB\x06\n" +
	"\x04bodyJ\x04\b\t\x10\x10\"\x95\x01\n" +
	"\vDamageDealt\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\rR\bsourceId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\rR\btargetId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\rR\x06amount\x12\x1a\n" +
	"\bcritical\x18\x04 \x01(\bR\bcritical\x12\x18\n" +
	"\aelement\x18\x05 \x01(\tR\aelement\"F\n" +
	"\n" +
	"EntityDied\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\rR\bentityId\x12\x1b\n" +
	"\tkiller_id\x18\x02 \x01(\rR\bkillerId\"d\n" +
	"\tSkillCast\x12\x1b\n" +
	"\tcaster_id\x18\x01 \x01(\rR\bcasterId\x12\x19\n" +
	"\bskill_id\x18\x02 \x01(\tR\askillId\x12\x1f\n" +
	"\vfacing_left\x18\x03 \x01(\bR\n" +
	"facingLeft\"9\n" +
	"\tExpGained\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x04R\x06amount\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total\"?\n" +
	"\aLevelUp\x12\x14\n" +
	"\x05level\x18\x01 \x01(\rR\x05level\x12\x1e\n" +
	"\vexp_to_next\x18\x02 \x01(\x04R\texpToNext\"g\n" +
	"\tLootTaken\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\rR\bentityId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x10\n" +
	"\x03qty\x18\x03 \x01(\rR\x03qty\x12\x12\n" +
	"\x04gold\x18\x04 \x01(\rR\x04gold\"?\n" +
	"\fPlayerJoined\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\rR\bentityId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\")\n" +
	"\n" +
	"PlayerLeft\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\rR\bentityId*E\n" +
	"\fInteractKind\x12\x1d\n" +
	"\x19INTERACT_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12INTERACT_KIND_LOOT\x10\x01*\x81\x01\n" +
	"\n" +
	"EntityKind\x12\x1b\n" +
	"\x17ENTITY_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ENTITY_KIND_PLAYER\x10\x01\x12\x13\n" +
	"\x0fENTITY_KIND_MOB\x10\x02\x12\x14\n" +
	"\x10ENTITY_KIND_DROP\x10\x03\x12\x13\n" +
	"\x0fENTITY_KIND_NPC\x10\x04*\x9b\x01\n" +
	"\vEntityField\x12\x1c\n" +
	"\x18ENTITY_FIELD_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ENTITY_FIELD_POS\x10\x01\x12\x14\n" +
	"\x10ENTITY_FIELD_VEL\x10\x02\x12\x16\n" +
	"\x12ENTITY_FIELD_FLAGS\x10\x03\x12\x15\n" +
	"\x11ENTITY_FIELD_ANIM\x10\x04\x12\x13\n" +
	"\x0fENTITY_FIELD_HP\x10\x05*\x95\x01\n" +
	"\n" +
	"EntityFlag\x12\x1b\n" +
	"\x17ENTITY_FLAG_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ENTITY_FLAG_GROUNDED\x10\x01\x12\x18\n" +
	"\x14ENTITY_FLAG_CLIMBING\x10\x02\x12\x1b\n" +
	"\x17ENTITY_FLAG_FACING_LEFT\x10\x03\x12\x19\n" +
	"\x15ENTITY_FLAG_JUMP_HELD\x10\x04B\x89\x01\n" +
	"\n" +
	"com.mmo.v1B\tGameProtoP\x01Z7github.com/ctrl-research/mmo/internal/wire/mmo/v1;mmov1\xa2\x02\x03MXX\xaa\x02\x06Mmo.V1\xca\x02\x06Mmo\\V1\xe2\x02\x12Mmo\\V1\\GPBMetadata\xea\x02\aMmo::V1b\x06proto3"

var (
	file_mmo_v1_game_proto_rawDescOnce sync.Once
	file_mmo_v1_game_proto_rawDescData []byte
)

func file_mmo_v1_game_proto_rawDescGZIP() []byte {
	file_mmo_v1_game_proto_rawDescOnce.Do(func() {
		file_mmo_v1_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mmo_v1_game_proto_rawDesc), len(file_mmo_v1_game_proto_rawDesc)))
	})
	return file_mmo_v1_game_proto_rawDescData
}

var file_mmo_v1_game_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_mmo_v1_game_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_mmo_v1_game_proto_goTypes = []any{
	(InteractKind)(0),     // 0: mmo.v1.InteractKind
	(EntityKind)(0),       // 1: mmo.v1.EntityKind
	(EntityField)(0),      // 2: mmo.v1.EntityField
	(EntityFlag)(0),       // 3: mmo.v1.EntityFlag
	(*Envelope)(nil),      // 4: mmo.v1.Envelope
	(*ClientMessage)(nil), // 5: mmo.v1.ClientMessage
	(*Cast)(nil),          // 6: mmo.v1.Cast
	(*Interact)(nil),      // 7: mmo.v1.Interact
	(*ServerMessage)(nil), // 8: mmo.v1.ServerMessage
	(*Hello)(nil),         // 9: mmo.v1.Hello
	(*Welcome)(nil),       // 10: mmo.v1.Welcome
	(*Kick)(nil),          // 11: mmo.v1.Kick
	(*Intent)(nil),        // 12: mmo.v1.Intent
	(*Ping)(nil),          // 13: mmo.v1.Ping
	(*Pong)(nil),          // 14: mmo.v1.Pong
	(*EntityState)(nil),   // 15: mmo.v1.EntityState
	(*EntityDelta)(nil),   // 16: mmo.v1.EntityDelta
	(*Snapshot)(nil),      // 17: mmo.v1.Snapshot
	(*Event)(nil),         // 18: mmo.v1.Event
	(*DamageDealt)(nil),   // 19: mmo.v1.DamageDealt
	(*EntityDied)(nil),    // 20: mmo.v1.EntityDied
	(*SkillCast)(nil),     // 21: mmo.v1.SkillCast
	(*ExpGained)(nil),     // 22: mmo.v1.ExpGained
	(*LevelUp)(nil),       // 23: mmo.v1.LevelUp
	(*LootTaken)(nil),     // 24: mmo.v1.LootTaken
	(*PlayerJoined)(nil),  // 25: mmo.v1.PlayerJoined
	(*PlayerLeft)(nil),    // 26: mmo.v1.PlayerLeft
}
var file_mmo_v1_game_proto_depIdxs = []int32{
	8,  // 0: mmo.v1.Envelope.server:type_name -> mmo.v1.ServerMessage
	5,  // 1: mmo.v1.Envelope.client:type_name -> mmo.v1.ClientMessage
	9,  // 2: mmo.v1.ClientMessage.hello:type_name -> mmo.v1.Hello
	12, // 3: mmo.v1.ClientMessage.intent:type_name -> mmo.v1.Intent
	13, // 4: mmo.v1.ClientMessage.ping:type_name -> mmo.v1.Ping
	6,  // 5: mmo.v1.ClientMessage.cast:type_name -> mmo.v1.Cast
	7,  // 6: mmo.v1.ClientMessage.interact:type_name -> mmo.v1.Interact
	0,  // 7: mmo.v1.Interact.kind:type_name -> mmo.v1.InteractKind
	10, // 8: mmo.v1.ServerMessage.welcome:type_name -> mmo.v1.Welcome
	17, // 9: mmo.v1.ServerMessage.snapshot:type_name -> mmo.v1.Snapshot
	18, // 10: mmo.v1.ServerMessage.event:type_name -> mmo.v1.Event
	14, // 11: mmo.v1.ServerMessage.pong:type_name -> mmo.v1.Pong
	11, // 12: mmo.v1.ServerMessage.kick:type_name -> mmo.v1.Kick
	15, // 13: mmo.v1.Welcome.self:type_name -> mmo.v1.EntityState
	1,  // 14: mmo.v1.EntityState.kind:type_name -> mmo.v1.EntityKind
	16, // 15: mmo.v1.Snapshot.entities:type_name -> mmo.v1.EntityDelta
	15, // 16: mmo.v1.Snapshot.entered:type_name -> mmo.v1.EntityState
	15, // 17: mmo.v1.Snapshot.self:type_name -> mmo.v1.EntityState
	25, // 18: mmo.v1.Event.player_joined:type_name -> mmo.v1.PlayerJoined
	26, // 19: mmo.v1.Event.player_left:type_name -> mmo.v1.PlayerLeft
	19, // 20: mmo.v1.Event.damage:type_name -> mmo.v1.DamageDealt
	20, // 21: mmo.v1.Event.died:type_name -> mmo.v1.EntityDied
	21, // 22: mmo.v1.Event.skill_cast:type_name -> mmo.v1.SkillCast
	22, // 23: mmo.v1.Event.exp_gained:type_name -> mmo.v1.ExpGained
	23, // 24: mmo.v1.Event.level_up:type_name -> mmo.v1.LevelUp
	24, // 25: mmo.v1.Event.loot_taken:type_name -> mmo.v1.LootTaken
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_mmo_v1_game_proto_init() }
func file_mmo_v1_game_proto_init() {
	if File_mmo_v1_game_proto != nil {
		return
	}
	file_mmo_v1_game_proto_msgTypes[1].OneofWrappers = []any{
		(*ClientMessage_Hello)(nil),
		(*ClientMessage_Intent)(nil),
		(*ClientMessage_Ping)(nil),
		(*ClientMessage_Cast)(nil),
		(*ClientMessage_Interact)(nil),
	}
	file_mmo_v1_game_proto_msgTypes[4].OneofWrappers = []any{
		(*ServerMessage_Welcome)(nil),
		(*ServerMessage_Snapshot)(nil),
		(*ServerMessage_Event)(nil),
		(*ServerMessage_Pong)(nil),
		(*ServerMessage_Kick)(nil),
	}
	file_mmo_v1_game_proto_msgTypes[14].OneofWrappers = []any{
		(*Event_PlayerJoined)(nil),
		(*Event_PlayerLeft)(nil),
		(*Event_Damage)(nil),
		(*Event_Died)(nil),
		(*Event_SkillCast)(nil),
		(*Event_ExpGained)(nil),
		(*Event_LevelUp)(nil),
		(*Event_LootTaken)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mmo_v1_game_proto_rawDesc), len(file_mmo_v1_game_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mmo_v1_game_proto_goTypes,
		DependencyIndexes: file_mmo_v1_game_proto_depIdxs,
		EnumInfos:         file_mmo_v1_game_proto_enumTypes,
		MessageInfos:      file_mmo_v1_game_proto_msgTypes,
	}.Build()
	File_mmo_v1_game_proto = out.File
	file_mmo_v1_game_proto_goTypes = nil
	file_mmo_v1_game_proto_depIdxs = nil
}
